export interface Movie {
  id: number;
  title: string;
  year: number;
  rating: number;
  genre: string[];
  poster: string;
  description: string;
}

export const movies: Movie[] = [
  {
    id: 1,
    title: 'John Wick',
    year: 2014,
    rating: 4.5,
    genre: ['Action'],
    poster: 'https://image.tmdb.org/t/p/w500/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg',
    description: 'An ex-hitman comes out of retirement to track down the gangsters who killed his dog and stole his car. A tale of vengeance and stylish action sequences.',
  },
  {
    id: 2,
    title: 'The Dark Knight',
    year: 2008,
    rating: 5,
    genre: ['Action', 'Drama'],
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    description: 'Batman faces his greatest challenge when the Joker wreaks havoc on Gotham City. A dark, psychological thriller that redefines superhero cinema.',
  },
  {
    id: 3,
    title: 'Taken',
    year: 2008,
    rating: 4.5,
    genre: ['Action', 'Thriller'],
    poster: 'https://m.media-amazon.com/images/M/MV5BMTM4NzQ0OTYyOF5BMl5BanBnXkFtZTcwMDkyNjQyMg@@._V1_SX300.jpg',
    description: 'A retired CIA agent travels across Europe and relies on his old skills to rescue his kidnapped daughter who has been caught by human traffickers. A relentless action thriller.',
  },
  {
    id: 4,
    title: 'The Hangover',
    year: 2009,
    rating: 4,
    genre: ['Comedy'],
    poster: 'https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    description: 'Three buddies wake up from a bachelor party in Las Vegas with no memory of the previous night and the missing groom. A hilarious quest to find out what happened.',
  },
  {
    id: 5,
    title: 'Superbad',
    year: 2007,
    rating: 4,
    genre: ['Comedy'],
    poster: 'https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg',
    description: 'Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry. A coming-of-age comedy classic.',
  },
  {
    id: 6,
    title: 'The Shawshank Redemption',
    year: 1994,
    rating: 5,
    genre: ['Drama'],
    poster: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. A powerful story of hope and friendship.',
  },
  {
    id: 7,
    title: 'Forrest Gump',
    year: 1994,
    rating: 4.5,
    genre: ['Drama', 'Romance'],
    poster: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
  },
 {
  id: 8,
  title: 'Mad Max: Fury Road',
  year: 2015,
  rating: 5,
  genre: ['Action', 'Adventure', 'Sci-Fi'],
  poster: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
  description: 'In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrannical warlord. Non-stop action, breathtaking stunts, and a visually stunning experience.',
}
,
  {
    id: 9,
    title: 'Interstellar',
    year: 2014,
    rating: 4.5,
    genre: ['Sci-Fi', 'Drama'],
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival. An epic journey through space and time exploring love and sacrifice.',
  },
  {
    id: 10,
    title: 'The Matrix',
    year: 1999,
    rating: 5,
    genre: ['Action', 'Sci-Fi'],
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. A revolutionary blend of philosophy and action.',
  },
  {
    id: 11,
    title: 'Get Out',
    year: 2017,
    rating: 4.5,
    genre: ['Horror', 'Thriller'],
    poster: 'https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
    description: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.',
  },
  {
    id: 12,
    title: 'A Quiet Place',
    year: 2018,
    rating: 4,
    genre: ['Horror', 'Sci-Fi'],
    poster: 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
    description: 'A family must live in absolute silence to hide from creatures that hunt by sound. A tense and innovative horror film about survival and parental love.',
  },
  {
    id: 13,
    title: 'Titanic',
    year: 1997,
    rating: 4.5,
    genre: ['Drama', 'Romance'],
    poster: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic. An epic romance tragedy that defined a generation.',
  },
  {
    id: 14,
    title: 'The Notebook',
    year: 2004,
    rating: 4,
    genre: ['Drama', 'Romance'],
    poster: 'https://image.tmdb.org/t/p/w500/qom1SZSENdmHFNZBXbtJAU0WTlC.jpg',
    description: 'A poor yet passionate young man falls in love with a rich young woman, giving her a sense of freedom, but they are separated because of their social differences.',
  },
  {
    id: 15,
    title: 'Pulp Fiction',
    year: 1994,
    rating: 5,
    genre: ['Drama', 'Thriller'],
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
  },
  {
    id: 16,
    title: 'The Silence of the Lambs',
    year: 1991,
    rating: 5,
    genre: ['Horror', 'Thriller'],
    poster: 'https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
    description: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer. A psychological thriller masterpiece.',
  },
  {
    id: 17,
    title: 'Avatar',
    year: 2009,
    rating: 4.5,
    genre: ['Action', 'Sci-Fi'],
    poster: 'https://m.media-amazon.com/images/I/61OUGpUfAyL._AC_SY679_.jpg',
    description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
  },
  {
    id: 18,
    title: 'La La Land',
    year: 2016,
    rating: 4.5,
    genre: ['Drama', 'Romance'],
    poster: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    description: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
  },
  {
    id: 19,
    title: 'The Godfather',
    year: 1972,
    rating: 5,
    genre: ['Drama', 'Thriller'],
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son. A landmark in cinematic storytelling.',
  },
  {
    id: 20,
    title: 'Deadpool',
    year: 2016,
    rating: 4.5,
    genre: ['Action', 'Comedy'],
    poster: 'https://image.tmdb.org/t/p/original/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
    description: 'A wisecracking mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for vengeance against the man who ruined his life.',
  },
  {
    id: 21,
    title: 'Gladiator',
    year: 2000,
    rating: 5,
    genre: ['Action', 'Drama'],
    poster: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery. An epic tale of honor and revenge.',
  },
  {
    id: 22,
    title: 'Parasite',
    year: 2019,
    rating: 5,
    genre: ['Drama', 'Thriller'],
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    description: 'A poor family schemes to become employed by a wealthy family by infiltrating their household, but simple greed threatens to expose and destroy everything.',
  },
];
